#!/usr/bin/env bash
# Wipes every cryptographic identity and generated runtime state this
# checkout has produced, so it's back to a fresh-clone state. Scope is
# deliberately limited to this checkout (never anything outside $ROOT) and
# to the file locations setup_mediator.sh/setup_registry.sh/start_dashboard.sh
# and the CLI actually write to by default - the same set .gitignore already
# tracks as "local, generated, possibly sensitive" (see .gitignore's comments).
#
# What this does NOT touch: keystores or journals you told the CLI to create
# at an absolute path outside this checkout (`/keystore create /some/other/
# place ...`) - this script only knows about its own directory, same
# boundary stopall.sh already holds to.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

YES=0
DRY_RUN=0
WITH_BUILD=0

usage() {
    cat <<EOF
usage: $(basename "$0") [options]

Wipes TLS identities, keystores/journals, local runtime state, and
operator-instance config generated by this checkout. Prompts for
confirmation and lists exactly what will be removed before touching
anything, unless -y/--yes is given.

Options:
  -y, --yes      don't prompt for confirmation
  -n, --dry-run  list what would be removed, remove nothing
  -b, --build    also remove build/ (forces a full rebuild next run)
  -a, --all      shorthand for --build
  -h, --help     show this help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -y|--yes) YES=1; shift ;;
        -n|--dry-run) DRY_RUN=1; shift ;;
        -b|--build|-a|--all) WITH_BUILD=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown option: $1" >&2; usage >&2; exit 1 ;;
    esac
done

targets=()   # "path|category" entries, path relative to $ROOT
add_if_present() {
    local path="$1" category="$2"
    if [[ -e "$path" ]]; then
        targets+=("$path|$category")
    fi
}

# 1. TLS server identities (private keys + certs).
add_if_present "$ROOT/certs" "TLS identity (private keys + certs)"

# 2. Keystores and their append-only journals/history, wherever they were
#    created inside this checkout (setup scripts and the CLI default to
#    creating them next to wherever they're run, not one fixed path).
while IFS= read -r -d '' path; do
    targets+=("$path|keystore / journal / history")
done < <(find "$ROOT" \
    \( -path "$ROOT/.git" -o -path "$ROOT/build" -o -path "$ROOT/.claude" \) -prune -o \
    \( -name "*.keystore" -o -name "*.keystore.journal.log" \
       -o -name "*.keystore.journal.head" -o -name "*.keystore.history" \) \
    -print0)

# 3. Local runtime state: dashboard/lobby/registry state files, the
#    webclient's local account list, and plain log output.
add_if_present "$ROOT/logs" "runtime state + logs (dashboard state, webclient accounts, *.log)"

# 4. Operator-instance config written by --init-config (may contain a real
#    fee receive address and local filesystem paths).
add_if_present "$ROOT/mediator.conf" "operator instance config"
add_if_present "$ROOT/registry.conf" "operator instance config"

# 5. Optional: build output, for a full reset rather than just crypto/state.
if [[ "$WITH_BUILD" -eq 1 ]]; then
    add_if_present "$ROOT/build" "build output (forces a rebuild next run)"
fi

if [[ "${#targets[@]}" -eq 0 ]]; then
    echo "nothing to clean - already at a fresh-clone state."
    exit 0
fi

echo "the following will be permanently removed:"
echo
for entry in "${targets[@]}"; do
    path="${entry%%|*}"
    category="${entry#*|}"
    size="$(du -sh "$path" 2>/dev/null | cut -f1)"
    printf "  %-6s %-55s [%s]\n" "$size" "${path#"$ROOT"/}" "$category"
done
echo

if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "dry run - nothing removed."
    exit 0
fi

if [[ "$YES" -ne 1 ]]; then
    read -r -p "proceed? this cannot be undone [y/N] " reply
    case "$reply" in
        y|Y|yes|YES) ;;
        *) echo "aborted, nothing removed."; exit 1 ;;
    esac
fi

# Stop anything from this checkout now that removal is actually confirmed -
# deleting a TLS key or state file out from under a running mediator/
# registry/dashboard just corrupts its next write, it doesn't stop it.
if [[ -x "$ROOT/stopall.sh" ]]; then
    "$ROOT/stopall.sh"
fi

for entry in "${targets[@]}"; do
    path="${entry%%|*}"
    rm -rf -- "$path"
done

echo "done. this checkout is back to a fresh-clone state"
if [[ "$WITH_BUILD" -eq 0 ]]; then
    echo "(build/ was left in place - pass --build for a full reset)."
fi
echo "re-run setup_mediator.sh / setup_registry.sh to generate new TLS identities."
