# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pat/p2p/tradep2p2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pat/p2p/tradep2p2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pat/p2p/tradep2p2/CMakeFiles /home/pat/p2p/tradep2p2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pat/p2p/tradep2p2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tradep2p

# Build rule for target.
tradep2p: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tradep2p
.PHONY : tradep2p

# fast build rule for target.
tradep2p/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/build
.PHONY : tradep2p/fast

#=============================================================================
# Target rules for targets named tradep2p_cli

# Build rule for target.
tradep2p_cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tradep2p_cli
.PHONY : tradep2p_cli

# fast build rule for target.
tradep2p_cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p_cli.dir/build.make CMakeFiles/tradep2p_cli.dir/build
.PHONY : tradep2p_cli/fast

#=============================================================================
# Target rules for targets named tradep2p-dashboard

# Build rule for target.
tradep2p-dashboard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tradep2p-dashboard
.PHONY : tradep2p-dashboard

# fast build rule for target.
tradep2p-dashboard/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p-dashboard.dir/build.make CMakeFiles/tradep2p-dashboard.dir/build
.PHONY : tradep2p-dashboard/fast

#=============================================================================
# Target rules for targets named tradep2p_unit_tests

# Build rule for target.
tradep2p_unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tradep2p_unit_tests
.PHONY : tradep2p_unit_tests

# fast build rule for target.
tradep2p_unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p_unit_tests.dir/build.make CMakeFiles/tradep2p_unit_tests.dir/build
.PHONY : tradep2p_unit_tests/fast

src/http_dashboard.o: src/http_dashboard.cpp.o
.PHONY : src/http_dashboard.o

# target to build an object file
src/http_dashboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p-dashboard.dir/build.make CMakeFiles/tradep2p-dashboard.dir/src/http_dashboard.cpp.o
.PHONY : src/http_dashboard.cpp.o

src/http_dashboard.i: src/http_dashboard.cpp.i
.PHONY : src/http_dashboard.i

# target to preprocess a source file
src/http_dashboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p-dashboard.dir/build.make CMakeFiles/tradep2p-dashboard.dir/src/http_dashboard.cpp.i
.PHONY : src/http_dashboard.cpp.i

src/http_dashboard.s: src/http_dashboard.cpp.s
.PHONY : src/http_dashboard.s

# target to generate assembly for a file
src/http_dashboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p-dashboard.dir/build.make CMakeFiles/tradep2p-dashboard.dir/src/http_dashboard.cpp.s
.PHONY : src/http_dashboard.cpp.s

src/lobby.o: src/lobby.cpp.o
.PHONY : src/lobby.o

# target to build an object file
src/lobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/lobby.cpp.o
.PHONY : src/lobby.cpp.o

src/lobby.i: src/lobby.cpp.i
.PHONY : src/lobby.i

# target to preprocess a source file
src/lobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/lobby.cpp.i
.PHONY : src/lobby.cpp.i

src/lobby.s: src/lobby.cpp.s
.PHONY : src/lobby.s

# target to generate assembly for a file
src/lobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/lobby.cpp.s
.PHONY : src/lobby.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p_cli.dir/build.make CMakeFiles/tradep2p_cli.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p_cli.dir/build.make CMakeFiles/tradep2p_cli.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p_cli.dir/build.make CMakeFiles/tradep2p_cli.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mediator.o: src/mediator.cpp.o
.PHONY : src/mediator.o

# target to build an object file
src/mediator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/mediator.cpp.o
.PHONY : src/mediator.cpp.o

src/mediator.i: src/mediator.cpp.i
.PHONY : src/mediator.i

# target to preprocess a source file
src/mediator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/mediator.cpp.i
.PHONY : src/mediator.cpp.i

src/mediator.s: src/mediator.cpp.s
.PHONY : src/mediator.s

# target to generate assembly for a file
src/mediator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/mediator.cpp.s
.PHONY : src/mediator.cpp.s

src/protocol.o: src/protocol.cpp.o
.PHONY : src/protocol.o

# target to build an object file
src/protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/protocol.cpp.o
.PHONY : src/protocol.cpp.o

src/protocol.i: src/protocol.cpp.i
.PHONY : src/protocol.i

# target to preprocess a source file
src/protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/protocol.cpp.i
.PHONY : src/protocol.cpp.i

src/protocol.s: src/protocol.cpp.s
.PHONY : src/protocol.s

# target to generate assembly for a file
src/protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/protocol.cpp.s
.PHONY : src/protocol.cpp.s

src/registry.o: src/registry.cpp.o
.PHONY : src/registry.o

# target to build an object file
src/registry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/registry.cpp.o
.PHONY : src/registry.cpp.o

src/registry.i: src/registry.cpp.i
.PHONY : src/registry.i

# target to preprocess a source file
src/registry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/registry.cpp.i
.PHONY : src/registry.cpp.i

src/registry.s: src/registry.cpp.s
.PHONY : src/registry.s

# target to generate assembly for a file
src/registry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/registry.cpp.s
.PHONY : src/registry.cpp.s

src/secure_channel.o: src/secure_channel.cpp.o
.PHONY : src/secure_channel.o

# target to build an object file
src/secure_channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/secure_channel.cpp.o
.PHONY : src/secure_channel.cpp.o

src/secure_channel.i: src/secure_channel.cpp.i
.PHONY : src/secure_channel.i

# target to preprocess a source file
src/secure_channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/secure_channel.cpp.i
.PHONY : src/secure_channel.cpp.i

src/secure_channel.s: src/secure_channel.cpp.s
.PHONY : src/secure_channel.s

# target to generate assembly for a file
src/secure_channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p.dir/build.make CMakeFiles/tradep2p.dir/src/secure_channel.cpp.s
.PHONY : src/secure_channel.cpp.s

tests/protocol_tests.o: tests/protocol_tests.cpp.o
.PHONY : tests/protocol_tests.o

# target to build an object file
tests/protocol_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p_unit_tests.dir/build.make CMakeFiles/tradep2p_unit_tests.dir/tests/protocol_tests.cpp.o
.PHONY : tests/protocol_tests.cpp.o

tests/protocol_tests.i: tests/protocol_tests.cpp.i
.PHONY : tests/protocol_tests.i

# target to preprocess a source file
tests/protocol_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p_unit_tests.dir/build.make CMakeFiles/tradep2p_unit_tests.dir/tests/protocol_tests.cpp.i
.PHONY : tests/protocol_tests.cpp.i

tests/protocol_tests.s: tests/protocol_tests.cpp.s
.PHONY : tests/protocol_tests.s

# target to generate assembly for a file
tests/protocol_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tradep2p_unit_tests.dir/build.make CMakeFiles/tradep2p_unit_tests.dir/tests/protocol_tests.cpp.s
.PHONY : tests/protocol_tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... tradep2p"
	@echo "... tradep2p-dashboard"
	@echo "... tradep2p_cli"
	@echo "... tradep2p_unit_tests"
	@echo "... src/http_dashboard.o"
	@echo "... src/http_dashboard.i"
	@echo "... src/http_dashboard.s"
	@echo "... src/lobby.o"
	@echo "... src/lobby.i"
	@echo "... src/lobby.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mediator.o"
	@echo "... src/mediator.i"
	@echo "... src/mediator.s"
	@echo "... src/protocol.o"
	@echo "... src/protocol.i"
	@echo "... src/protocol.s"
	@echo "... src/registry.o"
	@echo "... src/registry.i"
	@echo "... src/registry.s"
	@echo "... src/secure_channel.o"
	@echo "... src/secure_channel.i"
	@echo "... src/secure_channel.s"
	@echo "... tests/protocol_tests.o"
	@echo "... tests/protocol_tests.i"
	@echo "... tests/protocol_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

