[package]
name = "blindsig-prover"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "blindsig-prover"
path = "src/main.rs"

[dependencies]
methods = { path = "../methods" }
prover-core = { path = "../prover-core" }
risc0-zkvm = { version = "^3.0.6" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = { version = "2", features = ["serde"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
getrandom = "0.2"
