// Phase 4 setup helper: computes a REAL blinded target c=B*r+H(rho,mu)
// using the exact same functions the NIZK2 guest itself uses, so a C++
// dump program can sign this EXACT target via sign_target() (added
// specifically to support this: a real signer only ever signs an opaque
// blinded target, never a message it hashes itself) - giving a genuine,
// fully-consistent end-to-end instance rather than a fabricated one.
//
// Run: cargo run -p methods --release --example compute_blinded_target

use prover_core::{add_mod_q, g_of_r, h_of_rho_mu, hash_to_point, poly_mul::poly_mul_mod_q_schoolbook, N};
use std::fmt::Write as _;
use std::io::Write as _;

fn fmt_rust_array(out: &mut String, name: &str, values: &[i64]) {
    write!(out, "pub const {name}: [i64; {}] = [", values.len()).unwrap();
    for (i, v) in values.iter().enumerate() {
        if i != 0 {
            write!(out, ", ").unwrap();
        }
        write!(out, "{v}").unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn main() {
    // r = 0 vector: within r_in_bounds([-2,2]), and makes B*r=0 regardless
    // of B, so this example doesn't need to derive B from any particular
    // seed - any B works, use an arbitrary small nonzero one so B still
    // shows up meaningfully in the printed instance.
    let r: Vec<i32> = vec![0; N];
    let r_i64: Vec<i64> = vec![0; N];
    let b: Vec<i64> = (0..N as i64).map(|i| (i * 41 + 7) % 7933).collect();

    let rho = g_of_r(&r);
    let mu = "rust-crosscheck-blinded-message";

    let br = poly_mul_mod_q_schoolbook(&b, &r_i64);
    let h_digest = h_of_rho_mu(&rho, mu);
    let hash_term = hash_to_point(&h_digest);
    let c = add_mod_q(&br, &hash_term);

    let mut out = String::new();
    writeln!(out, "// Generated by examples/compute_blinded_target.rs - r=0, so this is a").unwrap();
    writeln!(out, "// degenerate-but-genuine blinding instance (B*r=0, c=H(rho,mu) exactly) -").unwrap();
    writeln!(out, "// still exercises the REAL guest computation path, just with a trivial r.").unwrap();
    fmt_rust_array(&mut out, "B", &b);
    writeln!(out, "pub const R: [i32; {N}] = [0; {N}];").unwrap();
    write!(out, "pub const RHO: [u8; 32] = [").unwrap();
    for (i, v) in rho.iter().enumerate() {
        if i != 0 {
            write!(out, ", ").unwrap();
        }
        write!(out, "{v}").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out, "pub const MU: &str = {mu:?};").unwrap();
    fmt_rust_array(&mut out, "C", &c);

    print!("{out}");
    // Written directly into methods/examples/data/ (not examples/ itself)
    // so cargo doesn't try to treat it as its own example binary (it has
    // no main()) - a real gap hit once already this session. Path is
    // relative to `cargo run`'s own invocation directory (this crate's
    // documented `cargo run -p methods --release --example
    // compute_blinded_target` is meant to be run from the WORKSPACE root,
    // blindsig-prover-q7933/, not from methods/ itself).
    std::fs::File::create("methods/examples/data/blinded_target_data.rs")
        .unwrap()
        .write_all(out.as_bytes())
        .unwrap();
    eprintln!("Wrote methods/examples/data/blinded_target_data.rs");
}
