// Dumps a REAL, genuinely-produced d=512 q=7933 signature (public key t,
// signature s0/s1, and the exact hash_to_point(message) target that was
// signed) as Rust-array-literal source text, for a real cross-language
// correctness test of the ported zkVM guest relation
// (blindsig-prover-q7933/prover-core/src/relation.rs) against this C++
// reference substrate's own already-validated sign()/verify(). Manual-
// only, same reasoning as every other diagnostic in this directory - this
// is a one-shot data-generation tool, not a regression test itself (the
// Rust side owns the actual regression test, using the output pasted in
// as a literal).

#include "tradep2p/blindsig_blns7933.hpp"
#include "tradep2p/blindsig_blns7933_sign.hpp"

#include <array>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <random>
#include <stdexcept>

#include "rust_blinded_target_c.inc"

namespace {

using namespace tradep2p::blns7933;

constexpr std::size_t kDegree = 512U;
constexpr std::int64_t kQ = 7933;

void print_rust_array(std::ostream& out, const char* name, const PolyQ& values) {
    out << "pub const " << name << ": [i64; " << values.size() << "] = [";
    for (std::size_t i = 0; i < values.size(); ++i) {
        if (i != 0) {
            out << ", ";
        }
        out << values[i];
    }
    out << "];\n";
}

} // namespace

int main() {
    try {
        const RingArithmetic ring(kDegree, kQ);
        NTRUTrapdoorGenerator generator(ring);
        CryptoRng rng(4); // same seed as sign_512_diagnostic.cpp, for a reproducible dump

        std::cerr << "Generating trapdoor (real d=512, ~230s)...\n";
        const TrapdoorKey key = generator.generate(rng);
        if (!generator.verify_ntru_relation(key)) {
            throw std::logic_error("dump: TrapGen produced an unverifiable key");
        }
        const PublicKey public_key = generator.derive_public(key);

        std::cerr << "Building signing tree (~30s)...\n";
        const HighReal target_sigma(static_cast<double>(Parameters::sigma));
        const auto tree = build_signing_tree(ring, key, target_sigma);

        const long double beta_s = static_cast<long double>(Parameters::sigma) *
                                   std::sqrt(2.0L * 2.0L * static_cast<long double>(kDegree));
        const BigInt norm_bound_squared(static_cast<long long>(beta_s * beta_s));

        const std::string message = "rust-crosscheck-dump-message";
        std::cerr << "Signing...\n";
        const Signature signature = sign(ring, key, *tree, message, norm_bound_squared, rng);

        const bool verified = verify(ring, public_key, message, signature, norm_bound_squared);
        if (!verified) {
            throw std::logic_error("dump: a genuinely produced signature failed to verify");
        }
        std::cerr << "Signed and verified. c++-side ||s||^2 check passed.\n";

        const PolyQ target = hash_to_point(ring, message);

        // Second signature, over the REAL blinded target the Rust NIZK2
        // guest itself computed (methods/examples/compute_blinded_target.rs) -
        // via sign_target(), the new raw-target API added specifically so a
        // real signer (or this cross-language test) never needs to hash a
        // message itself. Reuses the SAME trapdoor/tree already built above
        // (a tree only depends on the trapdoor key, not the target), so this
        // costs one more ffSampling call (~seconds), not another ~260s TrapGen.
        std::cerr << "Signing the real Rust-computed blinded target...\n";
        PolyQ blinded_target(kRustBlindedTargetC.begin(), kRustBlindedTargetC.end());
        const Signature blinded_signature =
            sign_target(ring, key, *tree, blinded_target, norm_bound_squared, rng);
        const bool blinded_verified =
            verify_target(ring, public_key, blinded_target, blinded_signature, norm_bound_squared);
        if (!blinded_verified) {
            throw std::logic_error("dump: the blinded-target signature failed to verify");
        }
        std::cerr << "Blinded-target signature verified.\n";

        std::ofstream out("rust_crosscheck_data.rs");
        out << "// Generated by rust_crosscheck_dump_512.cpp - real, genuinely-produced\n";
        out << "// d=512, q=7933 signatures (seed 4). Both T values below are identical\n";
        out << "// (same trapdoor keypair); c++-side verify()/verify_target() accepted both\n";
        out << "// signatures before this file was written.\n";
        out << "// (1) plain: message \"" << message << "\", target = hash_to_point(message).\n";
        print_rust_array(out, "T", public_key.t);
        print_rust_array(out, "S0", signature.s0);
        print_rust_array(out, "S1", signature.s1);
        print_rust_array(out, "TARGET_C", target);
        out << "// (2) blinded: target = the REAL c computed by\n";
        out << "// methods/examples/compute_blinded_target.rs (r=0, mu=\"rust-crosscheck-blinded-message\").\n";
        print_rust_array(out, "BLINDED_S0", blinded_signature.s0);
        print_rust_array(out, "BLINDED_S1", blinded_signature.s1);
        out.close();

        std::cerr << "Wrote rust_crosscheck_data.rs\n";
        return 0;
    } catch (const std::exception& e) {
        std::cerr << "dump: FAIL: " << e.what() << '\n';
        return 1;
    }
}
